create table public.roles
(
    role_id   integer generated by default as identity
        primary key,
    role_name varchar(255)
);



create table public.user_details
(
    user_id   integer      not null
        primary key,
    password  varchar(100) not null,
    user_name varchar(10)  not null
);



create table public.users_roles
(
    user_id integer not null
        constraint fkeo7hhumc8drtyngparrhpvadm
            references public.user_details,
    role_id integer not null
        constraint fkj6m8fwv7oqv74fcehir1a9ffy
            references public.roles,
    primary key (user_id, role_id)
);



create table public.flyway_schema_history
(
    installed_rank integer                 not null
        constraint flyway_schema_history_pk
            primary key,
    version        varchar(50),
    description    varchar(200)            not null,
    type           varchar(20)             not null,
    script         varchar(1000)           not null,
    checksum       integer,
    installed_by   varchar(100)            not null,
    installed_on   timestamp default now() not null,
    execution_time integer                 not null,
    success        boolean                 not null
);


insert into public.roles (role_id, role_name)
values (1,'ADMIN');
values (1,'USER');

insert into users_roles (user_id, role_id)
values (1,1);